defaults-iban-properties:
  country: DE
  size: 22
  withWhiteSpace: false
countries-iban-properties:
  country:
    -
      name: Deuscthland
      code: DE
      size: 22
      withWhiteSpace: false
    -
      name: Belgium
      code: BE
      size: 16
      withWhiteSpace: false
    -
      name: Frankreich
      code: FR
      size: 18
      withWhiteSpace: true
    -
      name: England
      code: EN
      size: 22
      withWhiteSpace: true
black-listed:
  countries:
    - BE
    - FR
check-specification:
   activeElementsToCheck:
     -  IBAN
     -  BLZ
     -  BANK
     -  KONTO
     -  BIC
   elements:
     -
       name: IBAN
       initialString: 'IBAN:'
       lastString: 'SWIFT'
       minSize: 22
       maxSize: 22
       withWhiteSpace: true
       blacklisted:
         - DE00000000033333333343441
         - DE27983773766664555355
         - DE27 9837 7376 6664 5553 50
         - DE15 3006 0601 0505 7807 80
     -
       name: BANK
       initialString: 'Bank:'
       lastString: 'Konto'
       minSize: 10
       maxSize: 30
       withWhiteSpace: true
       blacklisted:
         - TARGO BANK
         - Deutsche Bank
     -
       name: BLZ
       initialString: 'BLZ:'
       lastString: '\n'
       minSize: 10
       maxSize: 10
       withWhiteSpace:
       blacklisted:
         - 250 906 08
     -
       name: EMPFAENGER
       initialString: 'Empfänger:'
       lastString: 'IBAN'
       minSize:
       maxSize:
       withWhiteSpace:
       blacklisted:
         - Neo Anderson
         - Morpheus
     -
       name: BIC
       initialString: 'SWIFT/BIC:'
       lastString: '\n'
       minSize: 8
       maxSize: 8
       withWhiteSpace:
       blacklisted:
         -  DAEDEDDBBDC
     -
       name: KONTO
       initialString: 'Konto'
       lastString: 'BLZ'
       minSize: 8
       maxSize: 25
       withWhiteSpace:
       blacklisted:
         -  05 05 780780

