defaults-spec-properties:
  country: DE
  size: 22
  withWhiteSpace: false
countries-spec-properties:
  country:
    -
      name: Deuscthland
      code: DE
      size: 22
      withWhiteSpace: true
    -
      name: Belgium
      code: BE
      size: 16
      withWhiteSpace: false
    -
      name: Frankreich
      code: FR
      size: 18
      withWhiteSpace: true
    -
      name: England
      code: EN
      size: 22
      withWhiteSpace: true
black-listed:
  ibans:
    - DE00000000033333333343441
    - DE27983773766664555355
    - DE27 9837 7376 6664 5553 50
    - DE15 3006 0601 0505 7807 80
  countries:
    - BE
    - FR
check-specification:
   activeElementsToCheck:
     -  IBAN
   elements:
     -
       name: IBAN
       initialString: 'IBAN:'
       lastString: 'SWIFT'
       size: 22
       withWhiteSpace: true
       blacklisted:
     -
       name: BANK
       initialString: 'Bank:'
       lastString: 'Konto'
       size: 15
       withWhiteSpace: true
       blacklisted:
         - TARGO BANK
         - Deutsche Bank
     -
       name: BLZ
       initialString: 'BLZ:'
       lastString: '\n'
       size: 22
       withWhiteSpace: true
       blacklisted:
         - 250 800 01
     -
       name: EMPFAENGER
       initialString: 'Empfänger:'
       lastString: 'IBAN'
       size: 60
       withWhiteSpace: true
       blacklisted:
         - Neo Anderson
         - Morpheus
     -
       name: BIC
       initialString: 'SWIFT/BIC'
       lastString: '\n'
       size: 22
       withWhiteSpace: true
       blacklisted:

